### ISSUE TITLE
Prompt for GPT4V

### ISSUE THREAD

**Issue by LengSicong** [penghao-wu/vstar#11]
Hi authors, congrats on this great work!

May I know what your prompt is for evaluating GPT4V? We tested ourselves but found that the results were pretty different, especially the spatial relationship subset (where the accuracy is even far less than 50% for two-option MCQs).

**Comment by penghao-wu** [comment]
Hi, the prompt we used for evaluating GPT-4V is:
You will be given a question and several answer options. You should choose the correct option based on the image provided to you. You just need to answer the question and do not need any information about individuals. When you are not sure about the answer, just guess the most likely one. 
Question: XXX
Options: 
A. XXX
B. XXX
