### ISSUE TITLE
The visual Search Results don't present anything, and sometimes get errors.

### ISSUE THREAD

**Issue by liu-bohan** [penghao-wu/vstar#19]
Thank you for your great work!

I meet some problems when I use the Vstar app:

1. The visual Search Results(both text and visualization) don't present anything.
2. If my input prompt is a declarative sentence (e.g. "Segment the woman who will be blocked by the truck on her path forward.") it outputs with errors, but nothing error printed in terminal. Maybe exceed the time limitation?

<img width="935" alt="截屏2024-10-07 16 16 35" src="https://github.com/user-attachments/assets/e304b803-4bb9-45e7-8e61-54fd6b80e9cd">

<img width="1341" alt="截屏2024-10-07 15 49 01" src="https://github.com/user-attachments/assets/2e8d888f-d21b-4edb-8e08-572ee76e541a">

**Comment by penghao-wu** [comment]
- Our framework will activate the search process only when it needs specific visual information that is currently missing. In your first case, our VQA LLM thinks it can directly answer the question without searching for any additional information, so it provides the "Direct Answer" only.
- In your second case, our framework does not support this use case. However, it should output some specific error message in the terminal, could you please double-check that? Our visual search model alone can be used for referring segmentation/detection with a fixed format. If you want to use it for free-form reasoning segmentation, you might try models like [LISA](https://github.com/dvlab-research/LISA).

**Comment by liu-bohan** [comment]
> * Our framework will activate the search process only when it needs specific visual information that is currently missing. In your first case, our VQA LLM thinks it can directly answer the question without searching for any additional information, so it provides the "Direct Answer" only.
> * In your second case, our framework does not support this use case. However, it should output some specific error message in the terminal, could you please double-check that? Our visual search model alone can be used for referring segmentation/detection with a fixed format. If you want to use it for free-form reasoning segmentation, you might try models like [LISA](https://github.com/dvlab-research/LISA).

Thank you for the explanation! referring to #10 I comment out the `demo.queue()` in _app.py_, then the error issue shown in the second image has been resolved.

Another thing that I don't quite understand is that I see a `mode='segmentation'` part in the `inference` method of _visual_search.py_. I tried running _visual_search.py_ with the benchmark, but the results are as shown in the attached image. So, the`mode='segmentation'` here is not the segmentation I understand like LISA?

![search_result](https://github.com/user-attachments/assets/745321f6-a71d-45e1-865f-40622a6765c0)
![step_1_heatmap](https://github.com/user-attachments/assets/888d1190-366b-4b13-a23c-df162b01b747)
