### ISSUE TITLE
How much memory do I need to run the demo?

### ISSUE THREAD

**Issue by kexul** [penghao-wu/vstar#2]
Hi, I'd like to run the demo on a 4090 with 24G VRAM, is that enough?

**Comment by penghao-wu** [comment]
Hi, as we have two VLMs, the default setting will require around 28G memory. If you do need to run it on a single 4090, you might try to load and run the vqa model and visual search model separately.

**Comment by kexul** [comment]
Thanks! I enabled the `load_8bit` here: https://github.com/penghao-wu/vstar/blob/d10c0537b754ee14e33744c55649301e854aebd4/LLaVA/llava/model/builder.py#L26
Now it runs fine in my 24G memory.
Thanks for your awesome work and open source!
